version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - "/app/node_modules"
      - "./:/opt/lampp/htdocs/abc"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql-data: